---

# aws s3 
- name: "change dir"
  shell: "cd {{ PROJECT_PATH }};"
  ignore_errors: True

- name: "create touch file"
  shell: "touch {{ REMOTE | basename }}"
  when: command == "touchz"
  ignore_errors: True

- name: touch file to s3
  register: result
  shell: "aws s3 cp {{ REMOTE | basename }} {{ REMOTE }}"
  when: command == "touchz"
  ignore_errors: True

- include: ../../../tasks/std.yml
  vars:
    skip_errors: True

- name: remote touch file
  shell: "rm -rf {{ REMOTE | basename }}"
  when: command == "touchz"
  ignore_errors: True

- name: put file to s3
  register: result
  shell: "aws s3 cp {{ LOCAL }} {{ REMOTE }}"
  when: command == "put"
  ignore_errors: True

- include: ../../../tasks/std.yml

- name: remove file from s3
  register: result
  shell: "aws s3 rm {{ REMOTE }}"
  when: command == "rm"
  ignore_errors: True

- include: ../../../tasks/std.yml

- name: remove file from s3
  register: result
  shell: "aws s3 rm {{ REMOTE }} --recursive"
  when: command == "rmr"
  ignore_errors: True

- include: ../../../tasks/std.yml

- name: ls file from s3 dir
  register: result
  shell: "aws s3 ls {{ REMOTE }}"
  when: command == "ls"
  ignore_errors: True

- include: ../../../tasks/std.yml

- name: test file from s3
  register: result
  shell: "aws s3 cp {{ REMOTE }} {{ REMOTE | basename }}"
  when: command == "test"
  ignore_errors: True

- include: ../../../tasks/std.yml
  vars:
    skip_errors: True

- name: delete test file
  shell: "rm {{ REMOTE | basename }}"
  when: command == "test"
  ignore_errors: True

- name: get file from s3
  register: result
  shell: "aws s3 cp {{ REMOTE }} {{ LOCAL }}"
  when: command == "get"
  ignore_errors: True

- include: ../../../tasks/std.yml

 