---
# hadoop-tools script

- hosts: local
  tags: 
    - dfs local
  gather_facts: false
  tasks:
    - name: "hadoop dfs {{ COMMAND }} {{ SOURCE }} {{ DEST }}"
      register: result
      shell: "cd {{ PROJECT_PATH }};{{ hadoop_home }}/bin/hadoop dfs {{ COMMAND }} {{ SOURCE }} {{ DEST }}"
      ignore_errors: True
    - include: tasks/std.yml

- hosts: remote
  tags:
    - dfs remote
  gather_facts: false
  vars:
    - remote_type: "{{ True if REMOTE_TYPE in valid_type else False }}"
    - valid_type: ["aws"]
    - command: "{{ COMMAND[1:] }}"
  roles:
    - { role: "dfs-{{ REMOTE_TYPE }}", command: "{{ command }}", when: remote_type }

- hosts: remote
  tags:
    - dfs remote
  gather_facts: false
  vars:
    - check_remote: "{{ False if REMOTE_TYPE else True }}"
  tasks:
    - name: "hadoop dfs {{ COMMAND }} {{ SOURCE }} {{ DEST }}"
      register: result
      shell: "cd {{ PROJECT_PATH }};{{ hadoop_home }}/bin/hadoop dfs {{ COMMAND }} {{ SOURCE }} {{ DEST }}"
      ignore_errors: True
      when: check_remote
    - include: tasks/std.yml

- hosts: local
  tags: 
    - base local
  gather_facts: false
  tasks:
    - name: "hadoop {{ CMD }} {{ COMMAND }} {{ PARAM }}"
      register: result
      shell: "cd {{ PROJECT_PATH }};{{ hadoop_home }}/bin/hadoop {{ CMD }} {{ COMMAND }} {{ PARAM }}"
      ignore_errors: True
    - include: tasks/std.yml

- hosts: remote
  tags: 
    - base remote
  gather_facts: false
  tasks:
    - name: "hadoop {{ CMD }} {{ COMMAND }} {{ PARAM }}"
      register: result
      shell: "cd {{ PROJECT_PATH }};{{ hadoop_home }}/bin/hadoop {{ CMD }} {{ COMMAND }} {{ PARAM }}"
      ignore_errors: True
    - include: tasks/std.yml